### ISSUE TITLE
Feature request: sonner toast component (notification stack)

### ISSUE THREAD

**Issue by T3sT3ro** [sek-consulting/solid-ui#122]
I very like the [sonner component present in the shadcn](https://ui.shadcn.com/docs/components/sonner) so I started looking into how it can be ported, and found that there exists a [solid-sonner counterpart](https://github.com/wobsoriano/solid-sonner) already. I think it would be very nice to have it in solid-ui as well!

**Comment by sek-consulting** [comment]
Thanks for the feature request :)

I'm still unsure if I want to include sonner since it looks like the repo is only managed by a single person and the last update was nearly 2 months ago. I don't want to have to remove it again once issues start coming in.

But if it at least has feature parity already I might think about it.

**Comment by sek-consulting** [comment]
decided to just add the component ^^
it's already live :)

**Comment by zaynOm** [comment]
It does not showing on the web site

**Comment by stefan-karger** [comment]
> It does not showing on the web site

https://www.solid-ui.com/docs/components/sonner

**Comment by T3sT3ro** [comment]
I bet he meant "Clicking it on the website doesn't show the toast", and I can confirm.

**Comment by zaynOm** [comment]
> I bet he meant "Clicking it on the website doesn't show the toast", and I can confirm. But that would better go into a separate bug report.

yep that's what I meant
