### ISSUE TITLE
NumberFields IncrementTrigger avd DecrementTrigger are eating focus from the input

### ISSUE THREAD

**Issue by Dakotys** [sek-consulting/solid-ui#126]
When clicking on increment/decrement buttons the focus state of the main input is lost and it causes flashing of the white focus ring, I sugest adding onMouseDown={(e) => e.preventDefault()} on those buttons

**Comment by sek-consulting** [comment]
Thanks for the feedback!
Since it works in the kobalte docs I compared the css with the tailwind classes I use and it seems switching from `focus-visible` to `focus-within` will do the trick, so no `preventDefault()` is needed.

Will fix it now. Should be live either today or tomorrow.

Sorry for the long wait.

**Comment by sek-consulting** [comment]
fix is deployed
unfortunatelly it seems like I introduced a small visual issue for the darkmode.  :D
