### ISSUE TITLE
[Question] Missing elements from shadcn

### ISSUE THREAD

**Issue by guillaumefont** [sek-consulting/solid-ui#62]
A few components are missing from shadcn, some are recent (drawer, carousel) but some are already a bit older, like the navigation menu. Is it by design or is it plan to port all components ?

Thanks

**Comment by sek-consulting** [comment]
Hi @guillaumefont,

since solid-ui is based on kobalte.dev I unfortunatelly am bound to the primitives it provides.
For specific stuff like the drawer I used corvu.dev so we might have some additional options there but it's still very new.

It's planned to have all the main components from shadcn/ui especially the date components and also the resize component.

**Comment by guillaumefont** [comment]
Great, thank you for the update !
